---
 - name: restarts switches with their new configuration
   shell: sleep 1 && shutdown -r 0
   async: 1
   poll: 0
   ignore_errors: true

 - name: Wait for switches to come back up
   local_action: wait_for port=22 host="{{ inventory_hostname }}" search_regex=OpenSSH delay=10  
